# ~/.config/tracebook/config.yaml

# Annotate each command block with the working directory
annotate_directory: true

# Where to store session Markdown files
output_dir: ~/tracebook_sessions

# Where to store temporary files (e.g., for diffs)
temp_dir: /tmp/tracebook

# List of commands to filter out (won't be logged)
skip_commands:
  - cd
  - ls
  - pwd
  - clear
